In [82]:
from sklearn import tree
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [83]:
df = pd.read_csv('C:/data/DTdata_lar1.csv')

In [67]:
y = df.iloc[:, [1]]
x = df.iloc[:, 2:]

In [84]:
y = df.iloc[:, [1]]
x = df.iloc[:, 2:]

clf = tree.DecisionTreeClassifier()
clf = clf.fit(x, y)

#dataset 분리함
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

#데이터 표준화
sc = StandardScaler()
sc.fit(x_train)

#표준화된 데이터셋
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

In [62]:
clf = BaggingClassifier(base_estimator=DecisionTreeClassifier())

In [63]:
test = clf.fit(x_train, y_train)

test.score(x_test, y_test)

C:\Anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8179449601042176

In [85]:
com_tree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)
com_tree.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [86]:
from sklearn.metrics import accuracy_score

y_pred_tr = com_tree.predict(x_test)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred_tr))

Accuracy: 0.73

,기업이름,부도여부,공시,투자,이사,증권,감사,코스닥,거래,상장,...,한도액,법원,우려,신용,회계법인,검찰,횡령,부도,자금난,파산
0,지투하이소닉,1,1,0,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
1,지투하이소닉,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,1,0,0,0
2,지투하이소닉,1,1,1,1,0,0,1,1,1,...,0,0,0,0,0,1,1,0,0,0
3,지투하이소닉,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,지투하이소닉,1,1,0,1,1,0,1,1,1,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27375,LG텔레콤,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27376,LG텔레콤,0,0,1,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
27377,LG텔레콤,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27378,LG텔레콤,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27379,LG텔레콤,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

--------------------------------------------------------------------------------------

In [75]:
from sklearn import tree
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [79]:
df = pd.read_csv('C:/data/DTdata_lar1.csv')

In [80]:
y = df.iloc[:, [1]]
x = df.iloc[:, 2:]


#dataset 분리함
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

rf=RandomForestClassifier(random_state=0)
rf.fit(x_train,y_train)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [81]:
pred = rf.predict(x_test)
print('Accuracy: %.2f' % accuracy_score(y_test, pred))

Accuracy: 0.81